apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger-tracing:16686
    isDefault: false
    editable: true
    jsonData:
      nodeGraph:
        enabled: true

  - name: PostgreSQL-Audit
    type: postgres
    uid: postgres-audit
    access: proxy
    url: postgres-audit-vault:5432
    user: audit_user
    secureJsonData:
      password: audit_password
    jsonData:
      database: banking_audit
      sslmode: disable
      postgresVersion: 1600
    editable: true
